In [1]:
import numpy as np

In [2]:
v= np.array([1,2,3])

A= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [3]:
#Tensor has a depth of 3, Height of 2 and a width of 3
T = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18]]])

In [4]:
print("Vector:",v)
print("\n")
print("Matrix:",A)
print("\n")
print("Tensor:",T)

Vector: [1 2 3]


Matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]


Tensor: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
