In [1]:
import numpy as np
 
# Identitty(hehe) matrix of size 2
b = np.eye(2, dtype = float)
print("Matrix b : \n", b)
 
#4 rows and 5 columns
a = np.eye(4, 5, k = -1)
print("\nMatrix a : \n", a)

Matrix b : 
 [[1. 0.]
 [0. 1.]]

Matrix a : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [2]:
#for the upper diagonal, k takes a positive value
a = np.eye(4, 5, k = 1)
print("\nMatrix a : \n", a)


Matrix a : 
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
#for the main diagonal, k is 0.
a = np.eye(4, 5, k = 0)
print("\nMatrix a : \n", a)


Matrix a : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
