In [1]:
import numpy as np

In [3]:
v3 = np.array([0, 1, 2])
v4 = np.array([1, 0, 1])
v5 = np.array([2, 3, 5])
matrix_span_check = np.vstack([v3, v4, v5])

In [6]:
print(matrix_span_check)

basis_vectors=np.eye(3)
print("\n the basis vectors are:", basis_vectors)

[[0 1 2]
 [1 0 1]
 [2 3 5]]

 the basis vectors are: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
print(matrix_span_check.T)

#the .T method will transpose our matrix

[[0 1 2]
 [1 0 3]
 [2 1 5]]


In [12]:
is_vector_in_span = np.linalg.matrix_rank(matrix_span_check) == np.linalg.matrix_rank(matrix_span_check.T)
print(np.linalg.matrix_rank(matrix_span_check))
print(np.linalg.matrix_rank(matrix_span_check.T))

3
3


In [10]:
print(is_vector_in_span)

True
