In [1]:
import numpy as np
v= np.array([1,2,3])

A= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [2]:
T = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18]]])

In [5]:
#let us now perform some basic operations 

result_add= v + np.array([4,5,6])

result_sub=v - np.array([4,5,6])

#now declare a scalar and multiply our vector with it 
scalar=2
result_scalar_mul= scalar*v

In [6]:
print(result_add)

print(result_sub)

print(result_scalar_mul)

[5 7 9]
[-3 -3 -3]
[2 4 6]


In [7]:
#generate a random matrix
B=np.random.rand(3,3)

#this command then generates a random 3x3 matrix

In [8]:
print(B)
print(A+B)

[[0.10005945 0.15358311 0.11375023]
 [0.22764429 0.68724018 0.81310238]
 [0.08620704 0.09745134 0.9748569 ]]
[[1.10005945 2.15358311 3.11375023]
 [4.22764429 5.68724018 6.81310238]
 [7.08620704 8.09745134 9.9748569 ]]


In [9]:
#to perform matrix multiplication, we simply take the dot product of the two matrices

result_mat_mul= np.dot(A,B)

print(result_mat_mul)

[[ 0.81396917  1.82041749  4.6645257 ]
 [ 2.05570154  4.63524137 10.36965425]
 [ 3.29743391  7.45006526 16.07478279]]
