In [1]:
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


In [2]:

# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])

[11]


In [3]:
#negative slicing of a one-dimensional array
from numpy import array
data = array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


In [4]:
#MORE FUCKING SLICING
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[1:4])

#this is so much fun lol

[22 33 44]


In [12]:
# split input and output data
from numpy import array
# define array
data = array([
	[11, 22, 33],
	[44, 55, 66],
	[77, 88, 99]])
# separate data
X, y = data[:, :], data[:, 1]
print(X)
print(y)

Z, W= data[:, :1], data[:, 1:]

#play around with the syntax, fun stuff

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[22 55 88]


In [14]:
# split train and test data
from numpy import array
# define array
data = array([
	[11, 22, 33],
	[44, 55, 66],
	[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

#same fucking thing, masked as a variable. HAVE AT IT YA FILTHY ANIMALS

[[11 22 33]
 [44 55 66]]
[[77 88 99]]
