In [2]:
from numpy import array
import torch

#to stack and create array stacks horizontally and vertically.

In [3]:
l= [1,2,4]

a= array(l)
print(a)

[1 2 4]


In [4]:
print(a.shape)

print(a.dtype)


(3,)
int32


In [5]:
from numpy import empty 

a= empty([3,3,3])

In [6]:
print(a)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [1.02359984e-306 1.89146896e-307 7.56571288e-307]
  [3.11525958e-307 1.24610723e-306 1.37962320e-306]]

 [[1.29060871e-306 2.22518251e-306 1.33511969e-306]
  [1.78022342e-306 1.05700345e-307 3.11525958e-307]
  [1.69118108e-306 8.06632139e-308 1.20160711e-306]]

 [[1.69119330e-306 1.60218491e-306 1.00137661e-307]
  [9.79101761e-307 1.11260348e-306 1.33511562e-306]
  [7.23188049e-308 8.34402697e-308 8.91238232e-313]]]


In [7]:
from numpy import zeros

a=zeros([2,2])
print(a)

[[0. 0.]
 [0. 0.]]


In [8]:
from numpy import ones 
a=ones([3,3])

print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
from numpy import array, vstack 

In [10]:
a = array([[1, 2], [3, 4]])
b = array([[5, 6], [7, 8]])

c=vstack([a,b])

print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
print(c.shape)

(4, 2)


In [19]:
from numpy import array, hstack

a=array([[1, 2], [3, 4]])
b=array([[5, 6], [7,8],])

c=hstack([a,b])
print(c)

print(c.shape, c.dtype)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4) int32
