In [5]:
import torch 

In [6]:
torch.randn((2,3,5))

tensor([[[-0.3384,  2.1788, -0.9354,  0.8547,  1.1262],
         [-0.7549, -0.5107,  0.7220, -0.3474,  0.8390],
         [ 1.7354,  1.2667, -0.9652, -0.5518,  1.1034]],

        [[ 0.1506,  1.6516, -1.2644, -0.5240, -0.6791],
         [-1.8960,  0.2883, -0.5237,  1.1870, -0.1555],
         [-1.1609,  1.1445,  0.8249,  0.4653,  0.0467]]])

In [7]:
x = torch.tensor([1, 2, 4, 8], dtype=torch.float32)
y = torch.ones_like(x) * 2
print('x =', x)
print('x + y', x + y)
print('x - y', x - y)
print('x * y', x * y)
print('x / y', x / y)

x = tensor([1., 2., 4., 8.])
x + y tensor([ 3.,  4.,  6., 10.])
x - y tensor([-1.,  0.,  2.,  6.])
x * y tensor([ 2.,  4.,  8., 16.])
x / y tensor([0.5000, 1.0000, 2.0000, 4.0000])


### ``torch.randn()`` initialises your matrices with random numbers.

#### ``torch.ones_like()`` basically takes another tensor as an argument, and produces a tensor full of ones based on the size, dimensions and datatypes of the tensor that is passed as an argument.


In [8]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [9]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]], dtype=torch.float32)
print(x.dtype)
print(y)
torch.mm(x, y.t())

torch.float32
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor([[ 18.,  20.,  10.],
        [ 58.,  60.,  50.],
        [ 98., 100.,  90.]])

#### ``torch.exp()`` returns every element ``i`` in the tensor and then $e^i$ is returned.