In [6]:
import torch 

In [7]:
x= torch.arange(12, dtype=torch.float32)

x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [8]:
print(x.size(), x.shape)

torch.Size([12]) torch.Size([12])


In [9]:
x= x.reshape((3,4))

### ``torch.reshape()`` is seriously cool. If you can't perform division to figure out the rows and columns you would need to fit in the prescribed tensor, you can simply pass -1 as a dimension argument to let torch figure out how many rows or columns you actually need.

In [10]:
x= x.reshape(-1,4)

x= x.reshape(3,-1)

In [11]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
torch.FloatTensor(2,3)

tensor([[8.1352e-31, 1.1308e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

#### the ``torch.FloatTensor()``,``torch.Tensor()`` and ``torch.empty()`` methods are all the same. .Tensor() is the default tensor function with no specifics about the data type.

#### It also performs the exact same task as ``numpy.empty()``

#### These methods simply grabs some memory, so don't confuse them for a zero matrix. It initialises with some bs value, but it doesn't go out of its way to specify anything unlike ``torch.zeros()`` which makes sure that your matrix is initialised with only zeros.

In [13]:
torch.Tensor(1,2)

tensor([[ 0.0000, 18.9802]])

In [14]:
torch.empty(2,3)

tensor([[8.1354e-31, 1.1308e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [15]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [17]:
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
y

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

#### You can also specify each and every value of your tensor just like in the ``numpy.array()`` method