In [1]:
import torch 

In [3]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

print('x + y = ', x + y)
print('x * y = ', x * y)
print('x / y = ', x / y)
print('x ** y = ', torch.pow(x,y))

x + y =  tensor([5.])
x * y =  tensor([6.])
x / y =  tensor([1.5000])
x ** y =  tensor([9.])


### Overflow and Underflow, are two issues with the ``torch.pow()`` method:

#### convert to float using ``.item()``

In [4]:
#generate a range of numbers within the tensor usimg .arange()

x= torch.arange(4)

print("x is:", x)

x is: tensor([0, 1, 2, 3])


#### This shit is compatible to **indexing** and all array methods in python. 

In [7]:
x[3]

print(x.shape)

len(x)

torch.Size([4])


4

In [8]:
a = 2

x = torch.tensor([1,2,3])

y = torch.tensor([10,20,30])

print(a * x)

print(a * x + y)

tensor([2, 4, 6])
tensor([12, 24, 36])


### ``a * x + y`` works like basic array operations.

$$A=\begin{pmatrix}
 a_{11} & a_{12} & \cdots & a_{1m} \\
 a_{21} & a_{22} & \cdots & a_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nm} \\
\end{pmatrix}$$

#### N rows and M columns in a matrix is made, and we can initialise them to zeros and ones.

In [9]:
#now, we can initialise a tensor and shape it into a matrix.

A= torch.arange(20, dtype=torch.float32).reshape((5,4))

print(A)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


In [10]:
# the .t() method will transpose the matrix

print(A.t())

tensor([[ 0.,  4.,  8., 12., 16.],
        [ 1.,  5.,  9., 13., 17.],
        [ 2.,  6., 10., 14., 18.],
        [ 3.,  7., 11., 15., 19.]])


In [12]:
X= torch.arange(24).reshape(2,3,4,1)
print("X.shape:", X.shape)

print("X=", X)

Y= torch.arange(24).reshape(2,3,4)
print(Y)


X.shape: torch.Size([2, 3, 4, 1])
X= tensor([[[[ 0],
          [ 1],
          [ 2],
          [ 3]],

         [[ 4],
          [ 5],
          [ 6],
          [ 7]],

         [[ 8],
          [ 9],
          [10],
          [11]]],


        [[[12],
          [13],
          [14],
          [15]],

         [[16],
          [17],
          [18],
          [19]],

         [[20],
          [21],
          [22],
          [23]]]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
