In [1]:
# broadcast scalar to one-dimensional array
from numpy import array
# define array
a = array([1, 2, 3])
print(a)
# define scalar
b = 2
print(b)
# broadcast
c = a + b
print(c)

#just add them, its not rocket science.


[1 2 3]
2
[3 4 5]


In [3]:
# broadcast scalar to two-dimensional array
from numpy import array
# define array
A = array([
	[1, 2, 3],
	[1, 2, 3]])
print(A)
# define scalar
b = 2
print(b)
# broadcast
C = A + b
print(C)

#again, scalars are the shit, they'll just become a 2d array with the same values stored in the variable being repeated

#AT EVERY INDEX.

#2 becomes [[2, 2, 2]
#          [2, 2, 2]]  

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [4]:
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
	[1, 2, 3],
	[1, 2, 3]])
print(A)
# define one-dimensional array
b = array([1, 2, 3])
print(b)
# broadcast
C = A + b
print(C)

#arrays do this too, they'll just repeat the row or column

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


In [5]:
# broadcasting error
from numpy import array
# define two-dimensional array
A = array([
	[1, 2, 3],
	[1, 2, 3]])
print(A.shape)
# define one-dimensional array
b = array([1, 2])
print(b.shape)
# attempt broadcast
C = A + b
print(C)

#yeh wala thoda jyada hi crayzy hogya bhai, its intuitive why this is messed up

(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 