In [3]:
#LETS RESHAPE THIS BITCH

from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)

#reshape is an object within array, array in itself has plenty of callables

#the shape simply changes 
print(data)

[11 22 33 44 55]
(5,)
(5, 1)
[[11]
 [22]
 [33]
 [44]
 [55]]


In [4]:
#reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)

print(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)
print(data)

[[11 22]
 [33 44]
 [55 66]]
(3, 2)
(3, 2, 1)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
