In [1]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

vr3 = matrix_rank(A)
print(vr3)

[1 2 3]
1
[0 0 0 0 0]
0
2


In [2]:
M0 = array([
[0,0],
[0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)

[[0 0]
 [0 0]]
0


In [3]:
M1 = array([
[1,2],
[1,2]])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)

[[1 2]
 [1 2]]
1


In [4]:
M2 = array([
[1,2],
[3,4]])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)

[[1 2]
 [3 4]]
2
